server:
  port: 8010


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/axondb
    username: root
    password: root
  
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create-drop
              
  data:
    mongodb:
      uri: mongodb://localhost/eventsourcing
      port: 27017
      
axon:
  serializer:
    messages: jackson
    general: jackson
    events: jackson